[package]
name = "rustygame"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10.0", features = ["trace"]}
bevy_editor_pls = "0.4.0"
bevy_rapier3d = "*"
bevy_egui = "*"

[toolchain]
channel = "nightly"
